TARGET = ARES

SOURCES = code.c motor_data.c traction.c utils.c buffer.c

#VESC_C_LIB_PATH=/home/nobodyx/Pulpit/VESC/DEMETER/vesc_pkg/c_libs/  //PC
VESC_C_LIB_PATH=/workspaces/DEMETER/vesc_pkg/c_libs/				 //codespaces

include $(VESC_C_LIB_PATH)rules.mk