TARGET = arc

SOURCES = code.c biquad.c kalman.c motor_data.c state.c traction.c utils.c proportional_gain.c

VESC_C_LIB_PATH=/home/nobodyx/Pulpit/VESC/DEMETER/vesc_pkg/c_libs/
include $(VESC_C_LIB_PATH)rules.mk